# Generated by Django 5.2.14 on 2026-05-21 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AthleteEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('athlete_id', models.IntegerField(db_index=True)),
                ('name', models.CharField(max_length=200)),
                ('sex', models.CharField(max_length=1)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('weight', models.IntegerField(blank=True, null=True)),
                ('team', models.CharField(max_length=120)),
                ('noc', models.CharField(max_length=3)),
                ('games', models.CharField(max_length=40)),
                ('year', models.IntegerField()),
                ('season', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=80)),
                ('sport', models.CharField(max_length=80)),
                ('event', models.CharField(max_length=200)),
                ('medal', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['noc'], name='demo_app_at_noc_376c8c_idx'), models.Index(fields=['sport'], name='demo_app_at_sport_50103d_idx'), models.Index(fields=['year'], name='demo_app_at_year_47d080_idx'), models.Index(fields=['season'], name='demo_app_at_season_188236_idx'), models.Index(fields=['medal'], name='demo_app_at_medal_0e4b3b_idx')],
            },
        ),
    ]
