# Generated by Django 5.2.14 on 2026-05-14 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=50)),
                ('product', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sold_at', models.DateTimeField()),
                ('sales_rep', models.CharField(blank=True, max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'indexes': [models.Index(fields=['region'], name='demo_app_sa_region_26c610_idx'), models.Index(fields=['category'], name='demo_app_sa_categor_adfcc8_idx'), models.Index(fields=['sold_at'], name='demo_app_sa_sold_at_436b46_idx')],
            },
        ),
    ]
